server:
  port: 9004

spring:
  data:
    mongodb:
      uri: mongodb://localhost/pharmacy

dataset:
  medicines:
    Pregnant: Vitamins
    DryEyes: Drops
    Headache: Panadol
    IronDeficiency: Folicron