server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://localhost/drhouse-accountancy
    username: accountance
    password: nacs
  jpa:
    hibernate:
      ddl-auto: update

dataset:
  costs:
    surgery: 100
    sleep: 50
    plasters: 30
    idk: 60
    laser: 200
    Vitamins: 20
    Drops: 10
    Panadol: 15
    Folicron: 25
